### ISSUE TITLE
No result for Movielens 100K Worked Example

### ISSUE THREAD

**Issue by ghost** [SeldonIO/seldon-server#23]
I am trying to run ml100k example. All things are all right but when I tape `seldon-cli api --client-name ml100k --endpoint /js/recommendations --item 50 --limit 4` and get this result

```
connecting to zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 [SUCCEEDED]
response code 200
{"size":0,"requested":4,"list":[]}
```

which is different from what is mentioned in the tutorial.

Could you help me please?
Nadia

**Comment by naddou14** [comment]
I have also an another question if possible: why seldon use both zookeeper and etcd while things are possible relying only on just etcd? Thank you in advance for your answer.

**Comment by cliveseldon** [comment]
Can you rerun the ml100k job:

cd kubernetes/conf/examples/ml100k
kubectl create -f ml100k-import.json

And provide the logs?

Regards zookeeper and etcd. We only use zookeeper in Seldon. Etcd is part of Kubernetes.

**Comment by Moonba** [comment]
`$ kubectl create -f ml100k-import.json
job "ml100k-import" created`

`$kubectl get jobs -l name=ml100k-import
NAME            DESIRED   SUCCESSFUL   AGE
ml100k-import   1                 1                    4m
`
Than when i run `seldon-cli api --client-name ml100k --endpoint /js/recommendations --item 50 --limit 4` I got this error :

`File "/opt/conda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='seldon-server', port=80): Max retries exceeded with url: /js/recommendations?type=1&item=50&limit=4&user=1&consumer_key=3BOJZ988Y840JTK5JE6C&jsonpCallback=j (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbdec89bf90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1`

This is it all : 

`$ bin/seldon-cli api --client-name ml100k --endpoint /js/recommendations --item 50 --limit 4
Traceback (most recent call last):
  File "/opt/conda/bin/seldon-cli", line 4, in <module>
    connecting to zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 [SUCCEEDED]
__import__('pkg_resources').run_script('seldon==2.0.2', 'seldon-cli')
  File "/opt/conda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 742, in run_script
  File "/opt/conda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 1667, in run_script
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/EGG-INFO/scripts/seldon-cli", line 5, in <module>
    seldon.cli.start_seldoncli()
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/__init__.py", line 3, in start_seldoncli
    cli_main.main()
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cli_main.py", line 351, in main
    cmds[cmd](opts,command_data, command_args)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cmd_api.py", line 206, in cmd_api
    actions["default"](gopts,command_data, opts)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cmd_api.py", line 191, in action_call
    call_js(gopts,command_data,opts,auth)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cmd_api.py", line 127, in call_js
    r = requests.get(url,params=params)
  File "/opt/conda/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='seldon-server', port=80): Max retries exceeded with url: /js/recommendations?type=1&item=50&limit=4&user=1&consumer_key=3BOJZ988Y840JTK5JE6C&jsonpCallback=j (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbdec89bf90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1
`
Thank you .

**Comment by cliveseldon** [comment]
It does look like a memory issue. Can you try increasing e.g.
minikube start --memory=10000

**Comment by Moonba** [comment]
Yes , it worked with 10GB memory allocation . Thank you !

**Comment by Moonba** [comment]
Yes , it worked with 10GB memory allocation . I got the desired output after executing `seldon-cli api --client-name ml100k --endpoint /js/recommendations --item 50 --limit 4`

but when i wanted to go through it step by step and reached the step to setup the schema using JSON: 
`seldon-cli attr --action apply --client-name ml100k --json attr.json` 
I got the error : 

`IOError: [Errno 2] No such file or directory: './attr.json'
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1`

Same error even though the file does exist under the seldon-server/docker/examples/ml100k directory , i retried with writing the whole path in the command but still same error msg that No such file or directory ! ? 

Same error with the following steps , but instead its "Invalid file[items.csv]"
`connecting to zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 [SUCCEEDED]
Invalid file[items.csv]
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1`

My machine is a MAC OSX ELCAPITAN , 16GB memory, so to "ensure we have a namesever for external DNS (seems to be required for local Docker running of Kubernetes)"
i can't use `  echo "nameserver 8.8.8.8" >> /etc/resolv.conf`
so i manually added `8.8.8.8 nameserver` to /etc/hosts .

Here's the whole log for the JSON schema: 

`connecting to zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 [SUCCEEDED]
Traceback (most recent call last):

  File "/opt/conda/bin/seldon-cli", line 4, in <module>
    __import__('pkg_resources').run_script('seldon==2.0.2', 'seldon-cli')
  File "/opt/conda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 742, in run_script
  File "/opt/conda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 1667, in run_script
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/EGG-INFO/scripts/seldon-cli", line 5, in <module>
    seldon.cli.start_seldoncli()
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/__init__.py", line 3, in start_seldoncli
    cli_main.main()
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cli_main.py", line 351, in main
    cmds[cmd](opts,command_data, command_args)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cmd_attr.py", line 234, in cmd_attr
    actions[action](command_data, opts)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cmd_attr.py", line 172, in action_apply
    store_json(command_data,opts)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.0.2-py2.7.egg/seldon/cli/cmd_attr.py", line 106, in store_json
    f = open(opts.json)
IOError: [Errno 2] No such file or directory: './attr.json'
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1`

**Comment by cliveseldon** [comment]
I think this is because you are trying to run a command in the seldon-control container and it does not have access to the local files on your system. One way would be to move the required files to a location that seldon-control can access such as the /seldon-data if you are running with hostPath.

We should make this clearer in the documentation.

**Comment by Moonba** [comment]
I'm sorry i think i didn't understand what you're pointing at ? I couldn't find /seldon-data subdirectory ? i didn't find it under seldom-server/ .
Yes ,I'm using HostPath . 
I moved ml-100k folder and the files in /Users/me/seldon-server/docker/examples/ml100k to /Users/me/seldon-server/kubernetes/conf/examples/ml100k  and nothing changed .

**Comment by cliveseldon** [comment]
The main thing is you need to create the files in /seldon-data where seldon-control can see them.
If you are using host-path with your local folder /seldon-data then you can run commands like below which I tested:

Create a folder /seldon-data/ml100k.
Create the atttrs.json in /seldon-data/ml100k with the values as described in the docs.
then asusming you have downloaded, unzipped and ran iconv as described in docs for raw data then:

cat <(echo 'id,title,release,url') <(cat ml-100k/u.item.utf8 | awk -F '|' '{printf("%d,\"%s\",\"%s\",\"%s\"\n",$1,$2,$3,$5)}') > /seldon-data/ml100k/items.csv
cat <(echo "id") <(cat ml-100k/u.user | cut -d'|' -f1) > /seldon-data/ml100k/users.csv
cat <(echo "user_id,item_id,value,time") <(cat ml-100k/ua.base | cut -f1,2,3,4 --output-delimiter=,) > /seldon-data/ml100k/actions.csv

and:

seldon-cli attr --action apply --client-name ml100k --json /seldon-data/ml100k/attrs.json 
seldon-cli import --action items --client-name ml100k --file-path /seldon-data/ml100k/items.csv 
seldon-cli import --action users --client-name ml100k --file-path /seldon-data/ml100k/items.csv 
seldon-cli import --action users --client-name ml100k --file-path /seldon-data/ml100k/users.csv 

You can then run MF and setup algs as described.

seldon-cli import --action actions --client-name ml100k --file-path /seldon-data/ml100k/actions.csv
