### ISSUE TITLE
seldon-cli attr --action apply doesnt pick up the attributes json file

### ISSUE THREAD

**Issue by shreyas87** [SeldonIO/seldon-server#34]
upon executing the following command in the command line : -
seldon-cli attr --action apply --client-name univision --json attr.json 
the following error occurs  - 
Traceback (most recent call last):
  File "/opt/conda/bin/seldon-cli", line 4, in <module>
    __import__('pkg_resources').run_script('seldon==2.1', 'seldon-cli')
  File "/opt/conda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
connecting to zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 [SUCCEEDED]
  File "/opt/conda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.1-py2.7.egg/EGG-INFO/scripts/seldon-cli", line 5, in <module>
    seldon.cli.start_seldoncli()
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.1-py2.7.egg/seldon/cli/__init__.py", line 3, in start_seldoncli
    cli_main.main()
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.1-py2.7.egg/seldon/cli/cli_main.py", line 355, in main
    cmds[cmd](opts,command_data, command_args)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.1-py2.7.egg/seldon/cli/cmd_attr.py", line 250, in cmd_attr
    actions[action](command_data, opts)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.1-py2.7.egg/seldon/cli/cmd_attr.py", line 210, in action_apply
    store_json(command_data,opts)
  File "/opt/conda/lib/python2.7/site-packages/seldon-2.1-py2.7.egg/seldon/cli/cmd_attr.py", line 106, in store_json
    f = open(opts.json)
IOError: [Errno 2] No such file or directory: 'attr.json'

the attr.json is present in the working directory 
Shreyass-MBP:univision_poc shreyassrinivasan$ pwd
/Users/shreyassrinivasan/seldon/univision_poc
Shreyass-MBP:univision_poc shreyassrinivasan$ ls
attr.json					syndication_report_20161215_to_20161223.csv
items.csv
Shreyass-MBP:univision_poc shreyassrinivasan$

**Comment by seldondev** [comment]
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale
